### ISSUE TITLE
live view not working

### ISSUE THREAD

**Issue by DanP27** [kopiro/homebridge-tapo-camera#152]
**Describe The Bug:**

all cameras added ok to homebridge and apple home, camera thumbnail loads and refreshes however cannot view live.

**To Reproduce:**

click on camera, loads, fails
**Expected behavior:**

shows live view
**Logs:**

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 3:56:22 PM] Twin Bedroom camera 7422 is running on port 35165.
[8/5/2024, 3:56:23 PM] Please add [Twin Bedroom camera 7422] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 3:56:23 PM] Finley Camera 2831 is running on port 35817.
[8/5/2024, 3:56:23 PM] Please add [Finley Camera 2831] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 3:56:23 PM] Roman Camera 383E is running on port 43017.
[8/5/2024, 3:56:23 PM] Please add [Roman Camera 383E] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 3:56:23 PM] Registering platform 'homebridge-ring.Ring'
[8/5/2024, 4:09:19 PM] [homebridge-tapo-camera] Launched child bridge with PID 1886
[8/5/2024, 4:09:19 PM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/5/2024, 4:09:19 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:09:19 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 4:09:19 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 4:09:19 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 4:09:20 PM] Finley Camera 2831 is running on port 45157.
[8/5/2024, 4:09:20 PM] Please add [Finley Camera 2831] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 4:09:20 PM] Twin Bedroom camera 7422 is running on port 36717.
[8/5/2024, 4:09:20 PM] Please add [Twin Bedroom camera 7422] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 4:09:20 PM] Roman Camera 383E is running on port 44485.
[8/5/2024, 4:09:20 PM] Please add [Roman Camera 383E] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 4:10:08 PM] [homebridge-tapo-camera] Launched child bridge with PID 2005
[8/5/2024, 4:10:09 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:10:09 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 4:10:09 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 4:10:09 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 4:10:09 PM] Registering platform 'homebridge-ewelink.eWeLink'
[8/5/2024, 4:16:14 PM] [homebridge-tapo-camera] Launched child bridge with PID 2656
[8/5/2024, 4:16:14 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:16:14 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 4:16:14 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 4:16:14 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 4:16:44 PM] [homebridge-tapo-camera] Launched child bridge with PID 2755
[8/5/2024, 4:16:45 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:16:45 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 4:16:45 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 4:16:45 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 4:16:46 PM] Registering platform 'homebridge-govee.Govee'
[8/5/2024, 4:56:47 PM] [homebridge-tapo-camera] Launched child bridge with PID 6244
[8/5/2024, 4:56:47 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:56:47 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 4:57:48 PM] [homebridge-tapo-camera] Launched child bridge with PID 6406
[8/5/2024, 4:57:49 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 4:57:49 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 5:52:25 PM] [homebridge-tapo-camera] Launched child bridge with PID 10454
[8/5/2024, 5:52:26 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:52:40 PM] [homebridge-tapo-camera] Launched child bridge with PID 10551
[8/5/2024, 5:52:41 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:52:54 PM] [homebridge-tapo-camera] Launched child bridge with PID 10652
[8/5/2024, 5:52:55 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:52:55 PM] Got SIGTERM, shutting down child bridge process...
[8/5/2024, 5:53:09 PM] [homebridge-tapo-camera] Launched child bridge with PID 10739
[8/5/2024, 5:53:10 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:53:23 PM] [homebridge-tapo-camera] Launched child bridge with PID 10829
[8/5/2024, 5:53:24 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:53:24 PM] Got SIGTERM, shutting down child bridge process...
[8/5/2024, 5:53:24 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 5:53:38 PM] [homebridge-tapo-camera] Launched child bridge with PID 10909
[8/5/2024, 5:53:39 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:53:53 PM] [homebridge-tapo-camera] Launched child bridge with PID 10999
[8/5/2024, 5:53:54 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 5:53:54 PM] Got SIGTERM, shutting down child bridge process...
[8/5/2024, 5:53:54 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 5:54:08 PM] [homebridge-tapo-camera] Launched child bridge with PID 11094
[8/5/2024, 5:54:09 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 6:03:41 PM] [homebridge-tapo-camera] Launched child bridge with PID 12222
[8/5/2024, 6:03:42 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.1 child bridge successfully
[8/5/2024, 6:03:42 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.

**Plugin Config:**

{
    "cameras": [
        {
            "name": "Finley Camera",
            "ipAddress": "192.168.1.211",
            "password": "x",
            "streamUser": "x",
            "streamPassword": x
            "disableEyesToggleAccessory": true,
            "disableAlarmToggleAccessory": true,
            "disableNotificationsToggleAccessory": true,
            "disableMotionDetectionToggleAccessory": true,
            "disableLEDToggleAccessory": true,
            "disableMotionSensorAccessory": false,
            "eyesToggleAccessoryName": "Privacy Mode"
        },
        {
            "name": "Roman Camera",
            "ipAddress": "192.168.1.23",
            "password": "x",
            "streamUser": "x",
            "streamPassword": "x",
            "disableEyesToggleAccessory": true,
            "disableAlarmToggleAccessory": true,
            "disableNotificationsToggleAccessory": true,
            "disableMotionDetectionToggleAccessory": true,
            "disableLEDToggleAccessory": true
        },
        {
            "name": "Twin Bedroom camera",
            "ipAddress": "192.168.1.105",
            "password": "x",
            "streamUser": "x",
            "streamPassword": x
            "disableStreaming": false,
            "disableEyesToggleAccessory": true,
            "disableAlarmToggleAccessory": true,
            "disableNotificationsToggleAccessory": true,
            "disableMotionDetectionToggleAccessory": true,
            "disableLEDToggleAccessory": true
        }
    ],
    "_bridge": {
        "username": "0E:54:1C:3C:16:BF",
        "port": 49089
    },
    "platform": "tapo-camera"
}

**Screenshots:**

**Environment:**

* **Plugin Version**: Installed: v2.4.1
* **Homebridge Version**: 
* **Node.js Version**:  Installed: v20.16.0
* **NPM Version**: 
* **Operating System**: Ubuntu Focal (20.04.5 LTS) windows 10 hyper v

**Comment by kopiro** [comment]
Looks like you have Node v18 - and I don't see a reason actually to not support Node v18 on the plugin - I'm fixing it in 2.4.1 - please upgrade and let me know

**Comment by DanP27** [comment]
thank you @kopiro for your quick reply, it still isnt working after upgrading though :(. i did get it to load twice out of 6 attempts but it wasnt showing a live feed just a single static image. 

latest logs:
[8/5/2024, 10:05:17 PM] [homebridge-tapo-camera] Restarting child bridge...
[8/5/2024, 10:05:17 PM] Got SIGTERM, shutting down child bridge process...
[8/5/2024, 10:05:22 PM] [homebridge-tapo-camera] Child bridge process ended
[8/5/2024, 10:05:22 PM] [homebridge-tapo-camera] Process Ended. Code: 143, Signal: null
[8/5/2024, 10:05:29 PM] [homebridge-tapo-camera] Restarting Process...
[8/5/2024, 10:05:30 PM] [homebridge-tapo-camera] Launched child bridge with PID 22248
[8/5/2024, 10:05:30 PM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/5/2024, 10:05:30 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.2 child bridge successfully
[8/5/2024, 10:05:30 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 10:05:30 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 10:05:30 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 10:05:32 PM] Roman Camera 383E is running on port 38603.
[8/5/2024, 10:05:32 PM] Please add [Roman Camera 383E] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:05:32 PM] Finley Camera 2831 is running on port 42421.
[8/5/2024, 10:05:32 PM] Please add [Finley Camera 2831] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:05:32 PM] Twin Bedroom camera 7422 is running on port 43527.
[8/5/2024, 10:05:32 PM] Please add [Twin Bedroom camera 7422] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:08:18 PM] [homebridge-tapo-camera] Restarting child bridge...
[8/5/2024, 10:08:18 PM] Got SIGTERM, shutting down child bridge process...
[8/5/2024, 10:08:23 PM] [homebridge-tapo-camera] Child bridge process ended
[8/5/2024, 10:08:23 PM] [homebridge-tapo-camera] Process Ended. Code: 143, Signal: null
[8/5/2024, 10:08:30 PM] [homebridge-tapo-camera] Restarting Process...
[8/5/2024, 10:08:30 PM] [homebridge-tapo-camera] Launched child bridge with PID 22447
[8/5/2024, 10:08:30 PM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/5/2024, 10:08:30 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.2 child bridge successfully
[8/5/2024, 10:08:30 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 10:08:30 PM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-tapo-camera) is running on port 49089.
[8/5/2024, 10:08:30 PM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/5/2024, 10:08:31 PM] Twin Bedroom camera 7422 is running on port 46571.
[8/5/2024, 10:08:31 PM] Please add [Twin Bedroom camera 7422] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:08:31 PM] Finley Camera 2831 is running on port 41847.
[8/5/2024, 10:08:31 PM] Please add [Finley Camera 2831] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:08:31 PM] Roman Camera 383E is running on port 42315.
[8/5/2024, 10:08:31 PM] Please add [Roman Camera 383E] manually in Home app. Setup Code: 786-05-170
[8/5/2024, 10:15:10 PM] [homebridge-tapo-camera] Launched child bridge with PID 161
[8/5/2024, 10:15:11 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.2 child bridge successfully
[8/5/2024, 10:15:11 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.
[8/5/2024, 10:18:01 PM] [homebridge-tapo-camera] Launched child bridge with PID 683
[8/5/2024, 10:18:02 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.4.2 child bridge successfully
[8/5/2024, 10:18:02 PM] Loaded 0 cached accessories from cachedAccessories.0E541C3C16BF.

**Comment by DanP27** [comment]
I've updated now to v2.4.4 and still not working

**Comment by minhkhoiii1997** [comment]
I also have the same issue. Live view only works 2/10 tries for me. And when it worked, it took a very very long time to load. 

Updated to 2.4.4 and still not working.

**Comment by spencercnorton** [comment]
I'm having the same issue - Only thing I see in the logs when I initiate the live feed is:

[9/1/2024, 5:39:15 PM] [homebridge-tapo-camera/Entrance Camera] [Entrance Camera] Starting video stream: native x native, native fps, ??? kbps (AAC-eld)
[9/1/2024, 5:39:47 PM] [homebridge-tapo-camera/Entrance Camera] [Entrance Camera] Stopped video stream.

**Comment by niquini** [comment]
I'm having the same issue

**Comment by forcedmeme** [comment]
I'm also having this issue. From the logs "FFmpeg exited with code: 8 and signal: null (Error)" looks like a problem with FFmpeg. I've verified that FFmpeg is installed.

To clarify, Apple Home can display a 'snapshot' of the camera feed as a thumbnail, but it can not open a live video feed.

**Comment by itomaldonado** [comment]
+1 same here. VLC and Tapo app both load the stream quite quickly ( <1 sec to load ) but Apple Home just loads for a few seconds then errors out with “No Response. This camera is not responding”.

But the thumbnails still load correctly every 10s or so.

**Comment by kopiro** [comment]
Hey, I've made some video options more clear regarding the video configurations. If your ffmpeg is crashing, most likely the wrong codec is set, try to go through config again and follow the advices I gave there.

**Comment by darkaeden** [comment]
Not sure if anyone solved. But i am having the same issue with a C225.
Snapshot are refreshing every 10sec or so, but livestreaming never happens.
In the logs "ffmpeg exited with code: 0 and signal: null (expected)".

**Comment by DanP27** [comment]
@darkaeden funilly enough i fixed it yesterday. I changed the codec in the
config to another option, x264 i think and that solved it.

**Comment by minhkhoiii1997** [comment]
@DanP27 Can you elaborate that please? Which codec option? I see there is a Video Codec option under Plugin config, but when I changed it to x264, it still doesn't work. It would be great if you could check the setting and send it to us. Thank you!

Also @kopiro link https://sunoo.github.io/homebridge-camera-ffmpeg/configs doesn't work anymore, so I don't know which setting should I set here.

Thank you

**Comment by DanP27** [comment]
libx264

**Comment by minhkhoiii1997** [comment]
You're a live saver! Thank you!! @DanP27

**Comment by strugglebrother** [comment]
I can also confirm that the link that is commonly referred to

https://sunoo.github.io/homebridge-camera-ffmpeg/configs

Is not working anymore, is there another link of the parameter settings that can be reached?

**Comment by seansfkelley** [comment]
https://sunoo.github.io/homebridge-camera-ffmpeg/configs moved to https://homebridge-plugins.github.io/homebridge-camera-ffmpeg/configs and I opened https://github.com/kopiro/homebridge-tapo-camera/pull/186 to update the links here.
